# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Study\MusicPlayer\code\Music\Widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import qtawesome
from utility import lyricsDisplayer

class Ui_MusicPlayer(object):
    def setupUi(self, MusicPlayer):
        MusicPlayer.setObjectName("MusicPlayer")
        MusicPlayer.resize(1500, 1200) 
        MusicPlayer.setMinimumSize(QtCore.QSize(1000, 800))
        MusicPlayer.setMaximumSize(QtCore.QSize(1500, 1200))
        # self.verticalLayout_2 = QtWidgets.QVBoxLayout(MusicPlayer)#此处将主窗口对象改为网格布局
        self.main_layout = QtWidgets.QGridLayout(MusicPlayer)
        #self.verticalLayout_2.setSpacing(7)
        self.main_layout.setObjectName("main_layout")
        
        self.left_widget = QtWidgets.QWidget()  # 创建左侧部件
        self.left_widget.setObjectName('left_widget')
        self.left_layout = QtWidgets.QGridLayout()  # 创建左侧部件的网格布局层
        self.left_widget.setLayout(self.left_layout) # 设置左侧部件布局为网格

        self.right_widget = QtWidgets.QWidget() # 创建右侧部件
        self.right_widget.setObjectName('right_widget')
        self.right_layout = QtWidgets.QGridLayout()
        self.right_widget.setLayout(self.right_layout) # 设置右侧部件布局为网格

        self.main_layout.addWidget(self.left_widget,0,0,12,4) # 左侧部件在第0行第0列
        self.main_layout.addWidget(self.right_widget,0,4,12,10) # 右侧部件在第0行第3列

        self.left_close = QtWidgets.QPushButton("") # 关闭按钮
        self.left_visit = QtWidgets.QPushButton("") # 空白按钮
        self.left_mini = QtWidgets.QPushButton("")  # 最小化按钮
        self.left_close.setFixedSize(25,25) # 设置关闭按钮的大小
        self.left_visit.setFixedSize(25,25)  # 设置按钮大小
        self.left_mini.setFixedSize(25,25) # 设置最小化按钮大小
        self.left_close.setStyleSheet('''QPushButton{background:#F76677;border-radius:5px;}QPushButton:hover{background:red;}''')
        self.left_visit.setStyleSheet('''QPushButton{background:#F7D674;border-radius:5px;}QPushButton:hover{background:yellow;}''')
        self.left_mini.setStyleSheet('''QPushButton{background:#6DDF6D;border-radius:5px;}QPushButton:hover{background:green;}''')
        self.left_close.setObjectName("CloseBtn")
        self.left_visit.setObjectName("RestoreBtn")
        self.left_mini.setObjectName("MiniBtn")
        self.left_layout.addWidget(self.left_mini, 0,2,1,1)
        self.left_layout.addWidget(self.left_visit, 0,1,1,1)
        self.left_layout.addWidget(self.left_close, 0,0,1,1)

        self.ImportSongBtn = QtWidgets.QPushButton(qtawesome.icon('fa.music',color='white'),"本地歌曲")
        self.ImportSongBtn.setObjectName('ImportSongBtn')
        # self.label = QtWidgets.QLabel(self.left_widget)
        # self.label.setObjectName("label")
        # self.label.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        # self.label.setMinimumSize(QtCore.QSize(0, 20))  # 设置最小高度
        # self.label.setMaximumSize(QtCore.QSize(200, 20))  # 设置最大高度
        self.SongList = QtWidgets.QListWidget(self.left_widget)
        # self.SongList.setMinimumSize(QtCore.QSize(80, 200))
        # self.SongList.setMaximumSize(QtCore.QSize(200, 200))
        self.SongList.setFixedSize(QtCore.QSize(380, 450)) 
        self.SongList.setSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        self.SongList.setObjectName("SongList")
        self.SongList.setStyleSheet('''
            QListWidget {
                background-color: #D3D3D3;  /* 使用一种浅灰色，比灰色背景略亮 */
                border: none;  /* 去掉边框 */
                padding: 5px;  /* 为内容提供一些内边距 */
            }
            QListWidget::item {
                background-color: transparent;  /* 每个项目保持透明，以配合背景颜色 */
                color: #333333;  /* 设置文本颜色为深灰色，易于阅读 */
            }
            QListWidget::item:selected {
                background-color: #B0C4DE;  /* 选中项目颜色，可以使用一种淡蓝色或其他柔和颜色 */
                color: white;  /* 选中项目的文本颜色 */
            }
        ''')
        self.RetriveSongBtn = QtWidgets.QPushButton(qtawesome.icon('fa.headphones',color='white'),"听歌识曲")
        self.RetriveSongBtn.setObjectName('RetriveSongBtn')

        self.left_layout.addWidget(self.ImportSongBtn, 1, 0,1,3)
        #self.left_layout.addWidget(self.label,2,0,1,3)
        self.left_layout.addWidget(self.SongList, 2, 0, 1, 4)
        self.left_layout.setRowStretch(2, 1)  # 允许 SongList 扩展
        self.left_layout.addWidget(self.RetriveSongBtn, 4, 0,1,3)
        
        self.left_widget.setStyleSheet('''
            QPushButton{border:none;color:white;}
            QPushButton#left_label{
                border:none;
                border-bottom:1px solid white;
                font-size:18px;
                font-weight:700;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            }
            QPushButton#ImportSongBtn:hover, QPushButton#RetriveSongBtn:hover{border-left:4px solid red;font-weight:700;}
            QWidget#left_widget{
                background:gray;
                border-top:1px solid white;
                border-bottom:1px solid white;
                border-left:1px solid white;
                border-top-left-radius:10px;
                border-bottom-left-radius:10px;
            }
        ''')

        self.frame = QtWidgets.QFrame(self.right_widget)
        #self.frame.setMinimumSize(QtCore.QSize(0, 100))
        #self.frame.setMaximumSize(QtCore.QSize(800, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        #frame中的布局：水平
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SearchLine = QtWidgets.QLineEdit(self.frame)
        #self.SearchLine.setMinimumSize(QtCore.QSize(0, 30))
        self.SearchLine.setObjectName("SearchLine")
        self.SearchLine.setStyleSheet(
            '''QLineEdit{
                    border:1px solid gray;
                    width:300px;
                    border-radius:10px;
                    padding:2px 4px;
            }''')
        self.horizontalLayout.addWidget(self.SearchLine)
        self.SearchBtn = QtWidgets.QPushButton(self.frame)
        #self.SearchBtn.setMinimumSize(QtCore.QSize(0, 30))
        #self.SearchBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.SearchBtn.setObjectName("SearchBtn")
        self.horizontalLayout.addWidget(self.SearchBtn)
        self.horizontalLayout.setStretch(0, 1)
        #self.verticalLayout_2.addWidget(self.frame)
        #frame在整个right中的位置设置
        self.right_layout.addWidget(self.frame,0,0,1,10)


        self.frame_2 = QtWidgets.QFrame(self.right_widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        # self.RetriveSongBtn = QtWidgets.QPushButton(self.frame_2)
        # self.RetriveSongBtn.setObjectName("RetriveSongBtn")
        # self.gridLayout_2.addWidget(self.RetriveSongBtn, 0, 0, 1, 1)
        # self.ImportSongBtn = QtWidgets.QPushButton(self.frame_2)
        # self.ImportSongBtn.setObjectName("ImportSongBtn")
        # self.gridLayout_2.addWidget(self.ImportSongBtn, 0, 1, 1, 1)

        #self.lyricsDisplayer = lyricsDisplayer()
        self.gridLayout_2.addWidget(MusicPlayer.lyricsDisplayer, 1, 0, 2, 10)

        self.MusicNameLbl = QtWidgets.QLabel(self.frame_2)
        self.MusicNameLbl.setObjectName("MusicNameLbl")
        self.gridLayout_2.addWidget(self.MusicNameLbl,3,0,1,1)

        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        #self.PlayBtn = QtWidgets.QPushButton(self.groupBox)
        #self.PlayBtn.setObjectName("PlayBtn")
        self.MusicPositionSlider = QtWidgets.QSlider(self.groupBox)
        self.MusicPositionSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MusicPositionSlider.setObjectName("MusicPositionSlider")
        self.MusicPositionSlider.setMinimumWidth(300)
        self.MusicPositionSlider.setStyleSheet(
            '''
            QSlider::groove:horizontal {
                border: 1px solid #999999;
                height: 8px; /* 轨道的高度 */
                background: #E0E0E0;
                margin: 2px 0;
                border-radius: 4px;
            }
            
            QSlider::handle:horizontal {
                background: #F76677; /* 滑块的颜色 */
                border: 1px solid #5c5c5c;
                width: 14px; /* 滑块的宽度 */
                margin: -4px 0; /* 上下位置调整 */
                border-radius: 7px;
            }
            
            QSlider::sub-page:horizontal {
                background: #FFB0B8; /* 已滑过的部分颜色 */
                border: 1px solid #777;
                height: 8px;
                border-radius: 4px;
            }
            
            QSlider::add-page:horizontal {
                background: #C4C4C4; /* 未滑过的部分颜色 */
                border: 1px solid #777;
                height: 8px;
                border-radius: 4px;
            }
            '''
        )
        self.gridLayout.addWidget(self.MusicPositionSlider, 0, 0, 1, 7)

        self.MusicTimeLbl = QtWidgets.QLabel(self.groupBox)
        self.MusicTimeLbl.setObjectName("MusicTimeLbl")
        self.gridLayout.addWidget(self.MusicTimeLbl, 0, 9, 1, 1)

        self.console_button_1 = QtWidgets.QPushButton(qtawesome.icon('fa.backward', color='#F76677'), "")
        self.console_button_2 = QtWidgets.QPushButton(qtawesome.icon('fa.forward', color='#F76677'), "")
        self.console_button_3 = QtWidgets.QPushButton(qtawesome.icon('fa.play', color='#F76677', font=18), "")
        self.console_button_3.setObjectName("PlayPauseBtn")
        self.console_button_2.setObjectName("ForwardBtn")
        self.console_button_1.setObjectName("BackwardBtn")
        self.console_button_3.setIconSize(QtCore.QSize(40, 40))
        self.groupBox.setStyleSheet('''
            QPushButton{
                border:none;
            }
            QSlider::chunk {
                background-color: #F76677;
            }
        ''')
        self.gridLayout.addWidget(self.console_button_1, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.console_button_2, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.console_button_3, 1, 1, 1, 1)
        #self.gridLayout.setAlignment(QtCore.Qt.AlignCenter) 
        #self.gridLayout.addWidget(self.PlayBtn, 1, 0, 1, 1)
        #self.StopBtn = QtWidgets.QPushButton(self.groupBox)
        #self.StopBtn.setObjectName("StopBtn")
        #self.gridLayout.addWidget(self.StopBtn, 1, 1, 1, 1)

        self.groupBox.setStyleSheet("""
            QGroupBox { 
                border: none; 
                background-color: white; 
                font: bold; 
            }
        """)
        self.gridLayout_2.addWidget(self.groupBox, 4, 0, 1, 10)

        self.right_layout.addWidget(self.frame_2,3,0,5,10)

        self.right_widget.setStyleSheet('''
            QWidget#right_widget{
                color:#232C51;
                background:white;
                border-top:1px solid darkGray;
                border-bottom:1px solid darkGray;
                border-right:1px solid darkGray;
                border-top-right-radius:10px;
                border-bottom-right-radius:10px;
            }
            QLabel#right_lable{
                border:none;
                font-size:16px;
                font-weight:700;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            }
        ''')

        self.main_layout.setSpacing(0)
        #self.right_layout.setStretch(2, 1)

        self.retranslateUi(MusicPlayer)
        QtCore.QMetaObject.connectSlotsByName(MusicPlayer)

    def retranslateUi(self, MusicPlayer):
        _translate = QtCore.QCoreApplication.translate
        MusicPlayer.setWindowTitle(_translate("MusicPlayer", "Widget"))
        self.SearchBtn.setText(_translate("MusicPlayer", "搜索"))
        #self.label.setText(_translate("MusicPlayer", "歌曲列表"))
        # self.RetriveSongBtn.setText(_translate("MusicPlayer", "听歌识曲"))
        # self.ImportSongBtn.setText(_translate("MusicPlayer", "导入歌曲"))
        #self.console_button_3.setText(_translate("MusicPlayer", "播放"))
        #self.StopBtn.setText(_translate("MusicPlayer", "停止"))
        self.MusicTimeLbl.setText(_translate("MusicPlayer", "0:00/0:00"))
        self.MusicNameLbl.setText(_translate("MusicPlayer", "当前无歌曲"))
